### ISSUE TITLE
Grep+awk % usage

### ISSUE THREAD

**Issue by p1r473** [garabik/pydf#5]
Hi,
I am trying to grep the usage% from pydf.
It works fine under old fashioned df
```
df -H | grep -vE "^Filesystem|tmpfs|cdrom" | awk '{print $5 " " $6}'
98% /
100% /snap/scrcpy/250
100% /snap/core18/1889
100% /snap/scrcpy/286
100% /snap/core18/2126
100% /snap/scrcpy/255
100% /snap/core18/1937
20% /boot
13% /var/log

```
However I cant it to work under pydf.. It sort of works but not fully.
```
pydf -H | grep -vE "^Filesystem|tmpfs|cdrom" | awk '{print $7 " "$1}'
 Filesystem
94.3 /dev/root
 /dev/mmcblk0p1
0 /dev/loop2
0 /dev/loop5
0 /dev/loop0
0 /dev/loop1
0 /dev/loop4
0 /dev/loop3
94.3 /dev/root

```

You can see it sort of works. it grabs the 94.3

**Comment by garabik** [comment]
There are ANSI colo(u)r codes confusing the `awk` command - see for yourself by `pydf -H | cat -v`.

The best way is probably `pydf --bw -H | grep -vE "^Filesystem|tmpfs|cdrom" | awk '{print $5 " "$1}' ` to force black&white mode (note that the percentage is the 5th column).

**Comment by p1r473** [comment]
Got it working with

`pydf -h --bw | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | grep -vE "Filesystem|tmpfs|cdrom"  | awk '{print $5 " "$7}'`

Even with --bw, there is still colors. So I had to strip out the colors. I think the colors were throwing it off.
